// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esubkryguvaftxfrzkyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzdWJrcnlndXZhZnR4ZnJ6a3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzU5MzcsImV4cCI6MjA3MDMxMTkzN30.MDFPVg6GCH0YVXVLECrxwObPJakLnRSLzgZ1W9MJ1EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});